### ISSUE TITLE
GET http://localhost:3000/node_modules/csvtojson/libs/core.js 404 (Not Found)

### ISSUE THREAD

**Issue by tombalcaen** [Keyang/node-csvtojson#182] opened 2017-06-30 12:33 UTC
Hi,
I'm new to angular and I'm getting this error. Could anyone explain to me how?

* I installed the npm package csvtojson like this. npm i --save csvtojson.

I can see it in my node_module.

![screen shot 2017-06-30 at 14 28 45](https://user-images.githubusercontent.com/29797792/27735571-9a1b4406-5da0-11e7-8683-322431bbc03d.png)

* after I  changed systemjs.config.js

![screen shot 2017-06-30 at 14 29 14](https://user-images.githubusercontent.com/29797792/27735611-d00ef83c-5da0-11e7-9e21-cf7f1ff9a6c9.png)

* changed app.module.ts

![screen shot 2017-06-30 at 14 29 01](https://user-images.githubusercontent.com/29797792/27735614-d3a685f0-5da0-11e7-84de-3b557e992d55.png)

and i changed my .ts file I will use the csvtojson in. so i added the import.

![screen shot 2017-06-30 at 14 32 53](https://user-images.githubusercontent.com/29797792/27735654-07bb0302-5da1-11e7-9a2e-6cb1a5b0fde0.png)

What am I missing? Thanks in advance

**Comment by Keyang** [comment] 2017-07-03 09:12
You cannot use it as Angular 2 module but as a Javascript library.
For now steps are:

1. Import `dist/csvtojson.js` to your `index.html`

```html
<script src ="node_modules/csvtojson/dist/csvtojson.js"></script>
```

2. In anywhere you want to use `csvtojson` e.g. a ng2 `Component`

```js
declare var csvtojson:any;

export class MyComponent{
    method1(){
     //use csvtojson here..
        csvtojson()
        .fromString(xxx)
    }
}


```

**Comment by Keyang** [comment] 2017-07-03 09:13
the fully support using `import` or `require` in browser will come in version `1.1.8`

Duplicate of #183

**Closed by Keyang** 2017-07-03 09:13 UTC
