### ISSUE TITLE
Stream mode does not produce an array of JSON

### ISSUE THREAD

**Issue by mcqj** [Keyang/node-csvtojson#321] opened 2019-05-21 16:38 UTC
I am not sure what the expected behaviour is.
My output is one JSON object per line with no wrapping array and no comma separators e.g.

{name:"Joe Bloggs",status:"alive"}
{name:"Alice Kay",status:"deceased"}

etc.

**Comment by GioLogist** [comment] 2019-05-31 05:29
+1 on this

**Comment by ushakov-ruslan** [comment] 2019-06-13 06:36
The same here. It's a huge problem.

**Comment by Keyang** [comment] 2019-06-20 19:58
Duplicate of #307 
Will be covered by 2.0.9

**Closed** 2019-06-26 21:51 UTC

**Comment by adams-family** [comment] 2019-11-19 22:26
Hi, I think that this ticket should not be closed because the array generated is syntactically incorrect, since it contains a comma after the last row:

Received result:
[
  { "Name": "Peter" },
  { "Name": "Anna" },
  { "Name": "Jean" },
]
Expected result:
[
  { "Name": "Peter" },
  { "Name": "Anna" },
  { "Name": "Jean" }
]

Using v 2.0.10.

**Comment by cdimascio** [comment] 2020-12-12 20:39
@adams-family the following issue exists for the trailing comma issue, https://github.com/Keyang/node-csvtojson/issues/333
